apiVersion: apps/v1
kind: Deployment
metadata:
  name: view
  labels:
    app: view
spec:
  replicas: 1
  selector:
    matchLabels:
      app: view
  template:
    metadata:
      labels:
        app: view
    spec:
      containers:
        - name: view
          image: view-microservice
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_INCLUDE
              value: "kubernetes"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: view
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: view
                  key: password
          resources:
            requests:
              cpu: "0.2"
              memory: 800Mi
            limits:
              cpu: "1.0"
              memory: 800Mi
          readinessProbe:
            httpGet:
              port: 8080
              path: /view/actuator/health
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 5
          livenessProbe:
            httpGet:
              port: 8080
              path: /view/actuator/info
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 5
          volumeMounts:
            - name: view-volume
              mountPath: /etc/secretspot
      volumes:
        - name: view-volume
          secret:
            secretName: view
      serviceAccountName: api-service-account