kind: ConfigMap
apiVersion: v1
metadata:
  name: view
data:
  server.port: "8080"
  server.servlet.contextPath: "/view"
  spring.cloud.kubernetes.discovery.all-namespaces: "true"
  management.endpoints.web.exposure.include: "health,info,metrics,prometheus"
  management.metrics.enable.all: "true"
  management.metrics.distribution.percentiles-histogram.http.server.requests: "true"
  management.metrics.distribution.sla.http.server.requests: "1ms,5ms"
  spring.output.ansi.enabled: "ALWAYS"
  spring.application.name: "VIEW MICROSERVICE"
  spring.mvc.static-path-pattern: "/static/**"
  spring.datasource.driverClassName: "org.postgresql.Driver"
  spring.datasource.url: "jdbc:postgresql://host.docker.internal:5433/view-database-mk"
  spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
  spring.jpa.hibernate.ddl-auto: "update"
  spring.redis.host: "redis.redis.svc.cluster.local"
  spring.redis.port: "6379"
  spring.redis.timeout: "10000ms"
  spring.redis.lettuce.pool.max-active: "8"
  spring.redis.lettuce.pool.max-wait: "-1ms"
  spring.redis.lettuce.pool.max-idle: "8"
  spring.redis.lettuce.pool.min-idle: "8"