apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gateway
    spec:
      containers:
      - image: gateway-microservice
        name: gateway-microservice
        imagePullPolicy: Never
        env:
          - name: SPRING_PROFILES_INCLUDE
            value: "kubernetes"
        readinessProbe:
          httpGet:
            port: 9090
            path: /actuator/health
          initialDelaySeconds: 60
          timeoutSeconds: 2
          periodSeconds: 20
          failureThreshold: 5
        livenessProbe:
          httpGet:
            port: 9090
            path: /actuator/info
          initialDelaySeconds: 60
          timeoutSeconds: 2
          periodSeconds: 20
          failureThreshold: 5
      serviceAccountName: api-service-account
status: {}
