kind: PersistentVolume
apiVersion: v1
metadata:
  name: database-operation-pv-volume
  labels:
    type: local
    app: database-operation
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database-operation-pv-claim
  labels:
    app: database-operation
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi