apiVersion: v1
kind: Service
metadata:
  name: database-operation
  labels:
    app: database-operation
spec:
  ports:
    - port: 5432
      protocol: TCP
  selector:
    app: database-operation
  type: ClusterIP